name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install from lockfile
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-lock.txt
          pip install -e .

#      - name: Install project (dev + mbqc extras)
#        run: |
#          python -m pip install --upgrade pip
#          pip install -e ".[dev,mbqc]"


      - name: Run tests with coverage
        run: |
          pytest           # The pyproject already enables --cov and creates coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true  # make CI red if upload fails
